server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: peoplesync-hrms-backend
  datasource:
    url: jdbc:h2:mem:peoplesyncdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

peoplesync:
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 86400000

logging:
  level:
    com.peoplesync.hrms: INFO
