// Enterprise Mock Data for PeopleSync HRMS

export const ROLES = {
  ADMIN: 'ADMIN',
  HR: 'HR',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

export const MOCK_CURRENT_USERS = {
  ADMIN: {
    id: 1,
    name: 'Eleanor Vance',
    email: 'eleanor.vance@peoplesync.io',
    role: ROLES.ADMIN,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    designation: 'Chief Technology Officer',
    department: 'Executive Board',
    employeeId: 'EMP-001',
    joinDate: '2020-01-15',
    location: 'San Francisco, CA',
  },
  HR: {
    id: 2,
    name: 'Marcus Sterling',
    email: 'marcus.sterling@peoplesync.io',
    role: ROLES.HR,
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    designation: 'Head of Human Resources',
    department: 'Human Resources',
    employeeId: 'EMP-002',
    joinDate: '2021-03-01',
    location: 'New York, NY',
  },
  MANAGER: {
    id: 3,
    name: 'Sophia Chen',
    email: 'sophia.chen@peoplesync.io',
    role: ROLES.MANAGER,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    designation: 'Engineering Lead',
    department: 'Engineering',
    employeeId: 'EMP-003',
    joinDate: '2021-08-10',
    location: 'Austin, TX',
  },
  EMPLOYEE: {
    id: 4,
    name: 'David Miller',
    email: 'david.miller@peoplesync.io',
    role: ROLES.EMPLOYEE,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    designation: 'Senior Frontend Engineer',
    department: 'Engineering',
    employeeId: 'EMP-004',
    joinDate: '2022-05-18',
    location: 'Remote, US',
  }
};

export const INITIAL_DEPARTMENTS = [
  {
    id: 1,
    name: 'Engineering',
    code: 'ENG',
    headName: 'Sophia Chen',
    employeeCount: 42,
    budget: '$1,450,000',
    location: 'Austin HQ & Remote',
    color: '#1F4D3B',
    description: 'Product development, architecture, cloud operations, and platform quality.',
  },
  {
    id: 2,
    name: 'Human Resources',
    code: 'HR',
    headName: 'Marcus Sterling',
    employeeCount: 14,
    budget: '$520,000',
    location: 'New York HQ',
    color: '#6B4F3B',
    description: 'Talent acquisition, employee wellness, compensation, and workplace culture.',
  },
  {
    id: 3,
    name: 'Product & Design',
    code: 'PRD',
    headName: 'Rachel Green',
    employeeCount: 18,
    budget: '$780,000',
    location: 'San Francisco, CA',
    color: '#2E7D57',
    description: 'UX research, UI architecture, product management, and brand identity.',
  },
  {
    id: 4,
    name: 'Sales & Marketing',
    code: 'MKT',
    headName: 'Jonathan Vance',
    employeeCount: 29,
    budget: '$1,100,000',
    location: 'Chicago, IL',
    color: '#F59E0B',
    description: 'Global enterprise growth, digital marketing, PR, and revenue operations.',
  },
  {
    id: 5,
    name: 'Finance & Legal',
    code: 'FIN',
    headName: 'Victoria Hastings',
    employeeCount: 10,
    budget: '$640,000',
    location: 'New York HQ',
    color: '#2563EB',
    description: 'Payroll compliance, financial audits, risk management, and legal governance.',
  }
];

export const INITIAL_EMPLOYEES = [
  {
    id: 1,
    employeeId: 'EMP-001',
    name: 'Eleanor Vance',
    email: 'eleanor.vance@peoplesync.io',
    phone: '+1 (555) 234-5678',
    department: 'Engineering',
    role: 'ADMIN',
    designation: 'Chief Technology Officer',
    status: 'ACTIVE',
    joinDate: '2020-01-15',
    salary: 195000,
    location: 'San Francisco, CA',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    skills: ['System Architecture', 'Java 21', 'Spring Cloud', 'Leadership'],
    leaveBalance: { casual: 8, sick: 10, annual: 15 },
  },
  {
    id: 2,
    employeeId: 'EMP-002',
    name: 'Marcus Sterling',
    email: 'marcus.sterling@peoplesync.io',
    phone: '+1 (555) 345-6789',
    department: 'Human Resources',
    role: 'HR',
    designation: 'Head of Human Resources',
    status: 'ACTIVE',
    joinDate: '2021-03-01',
    salary: 145000,
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    skills: ['Talent Strategy', 'Conflict Resolution', 'HR Analytics', 'Payroll'],
    leaveBalance: { casual: 6, sick: 7, annual: 12 },
  },
  {
    id: 3,
    employeeId: 'EMP-003',
    name: 'Sophia Chen',
    email: 'sophia.chen@peoplesync.io',
    phone: '+1 (555) 456-7890',
    department: 'Engineering',
    role: 'MANAGER',
    designation: 'Engineering Lead',
    status: 'ACTIVE',
    joinDate: '2021-08-10',
    salary: 165000,
    location: 'Austin, TX',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    skills: ['React 19', 'Node.js', 'Agile Coaching', 'PostgreSQL'],
    leaveBalance: { casual: 10, sick: 12, annual: 18 },
  },
  {
    id: 4,
    employeeId: 'EMP-004',
    name: 'David Miller',
    email: 'david.miller@peoplesync.io',
    phone: '+1 (555) 567-8901',
    department: 'Engineering',
    role: 'EMPLOYEE',
    designation: 'Senior Frontend Engineer',
    status: 'ACTIVE',
    joinDate: '2022-05-18',
    salary: 128000,
    location: 'Remote, US',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    skills: ['React', 'TypeScript', 'TailwindCSS', 'Framer Motion'],
    leaveBalance: { casual: 5, sick: 8, annual: 10 },
  },
  {
    id: 5,
    employeeId: 'EMP-005',
    name: 'Rachel Green',
    email: 'rachel.green@peoplesync.io',
    phone: '+1 (555) 678-9012',
    department: 'Product & Design',
    role: 'MANAGER',
    designation: 'VP of Product',
    status: 'ACTIVE',
    joinDate: '2021-11-05',
    salary: 172000,
    location: 'San Francisco, CA',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    skills: ['Product Vision', 'Figma', 'User Research', 'Roadmapping'],
    leaveBalance: { casual: 7, sick: 10, annual: 14 },
  },
  {
    id: 6,
    employeeId: 'EMP-006',
    name: 'Jonathan Vance',
    email: 'jonathan.vance@peoplesync.io',
    phone: '+1 (555) 789-0123',
    department: 'Sales & Marketing',
    role: 'MANAGER',
    designation: 'Sales Director',
    status: 'ACTIVE',
    joinDate: '2022-01-20',
    salary: 155000,
    location: 'Chicago, IL',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    skills: ['Enterprise Sales', 'HubSpot', 'Negotiation', 'CRM'],
    leaveBalance: { casual: 4, sick: 6, annual: 11 },
  },
  {
    id: 7,
    employeeId: 'EMP-007',
    name: 'Amara Okafor',
    email: 'amara.okafor@peoplesync.io',
    phone: '+1 (555) 890-1234',
    department: 'Human Resources',
    role: 'EMPLOYEE',
    designation: 'Talent Acquisition Specialist',
    status: 'ACTIVE',
    joinDate: '2023-02-14',
    salary: 92000,
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    skills: ['Sourcing', 'LinkedIn Recruiter', 'Interviewing'],
    leaveBalance: { casual: 9, sick: 10, annual: 15 },
  },
  {
    id: 8,
    employeeId: 'EMP-008',
    name: 'Liam Hemsworth',
    email: 'liam.h@peoplesync.io',
    phone: '+1 (555) 901-2345',
    department: 'Finance & Legal',
    role: 'EMPLOYEE',
    designation: 'Senior Accountant',
    status: 'ON_LEAVE',
    joinDate: '2022-09-01',
    salary: 105000,
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    skills: ['QuickBooks', 'Tax Audit', 'Financial Reporting'],
    leaveBalance: { casual: 2, sick: 4, annual: 8 },
  }
];

export const INITIAL_ATTENDANCE = [
  {
    id: 101,
    employeeId: 'EMP-001',
    employeeName: 'Eleanor Vance',
    department: 'Engineering',
    date: '2026-07-30',
    checkIn: '08:52 AM',
    checkOut: '05:45 PM',
    status: 'PRESENT',
    workHours: '8h 53m',
  },
  {
    id: 102,
    employeeId: 'EMP-002',
    employeeName: 'Marcus Sterling',
    department: 'Human Resources',
    date: '2026-07-30',
    checkIn: '09:05 AM',
    checkOut: '--:--',
    status: 'PRESENT',
    workHours: 'Active',
  },
  {
    id: 103,
    employeeId: 'EMP-003',
    employeeName: 'Sophia Chen',
    department: 'Engineering',
    date: '2026-07-30',
    checkIn: '09:32 AM',
    checkOut: '--:--',
    status: 'LATE',
    workHours: 'Active',
  },
  {
    id: 104,
    employeeId: 'EMP-004',
    employeeName: 'David Miller',
    department: 'Engineering',
    date: '2026-07-30',
    checkIn: '08:45 AM',
    checkOut: '--:--',
    status: 'PRESENT',
    workHours: 'Active',
  },
  {
    id: 105,
    employeeId: 'EMP-008',
    employeeName: 'Liam Hemsworth',
    department: 'Finance & Legal',
    date: '2026-07-30',
    checkIn: '--:--',
    checkOut: '--:--',
    status: 'ON_LEAVE',
    workHours: '0h 0m',
  }
];

export const INITIAL_LEAVE_REQUESTS = [
  {
    id: 201,
    employeeId: 'EMP-004',
    employeeName: 'David Miller',
    department: 'Engineering',
    leaveType: 'Annual Leave',
    startDate: '2026-08-04',
    endDate: '2026-08-08',
    days: 5,
    reason: 'Family vacation and personal downtime.',
    status: 'PENDING',
    appliedOn: '2026-07-28',
    managerNotes: '',
  },
  {
    id: 202,
    employeeId: 'EMP-008',
    employeeName: 'Liam Hemsworth',
    department: 'Finance & Legal',
    leaveType: 'Sick Leave',
    startDate: '2026-07-29',
    endDate: '2026-07-31',
    days: 3,
    reason: 'Medical recovery following doctor recommendations.',
    status: 'APPROVED',
    appliedOn: '2026-07-28',
    managerNotes: 'Approved. Get well soon!',
  },
  {
    id: 203,
    employeeId: 'EMP-007',
    employeeName: 'Amara Okafor',
    department: 'Human Resources',
    leaveType: 'Casual Leave',
    startDate: '2026-07-25',
    endDate: '2026-07-25',
    days: 1,
    reason: 'Personal urgent appointment.',
    status: 'APPROVED',
    appliedOn: '2026-07-22',
    managerNotes: 'Approved by HR Lead.',
  },
  {
    id: 204,
    employeeId: 'EMP-006',
    employeeName: 'Jonathan Vance',
    department: 'Sales & Marketing',
    leaveType: 'Unpaid Leave',
    startDate: '2026-07-15',
    endDate: '2026-07-16',
    days: 2,
    reason: 'Attending external sales summit in London.',
    status: 'REJECTED',
    appliedOn: '2026-07-10',
    managerNotes: 'Please claim as Business Travel Expense instead.',
  }
];

export const INITIAL_PAYROLL = [
  {
    id: 301,
    employeeId: 'EMP-001',
    employeeName: 'Eleanor Vance',
    department: 'Engineering',
    designation: 'Chief Technology Officer',
    month: 'July 2026',
    basicSalary: 12000,
    allowances: 4250,
    deductions: 1200,
    tax: 1800,
    netSalary: 13250,
    status: 'PAID',
    paymentDate: '2026-07-25',
  },
  {
    id: 302,
    employeeId: 'EMP-002',
    employeeName: 'Marcus Sterling',
    department: 'Human Resources',
    designation: 'Head of Human Resources',
    month: 'July 2026',
    basicSalary: 9000,
    allowances: 3000,
    deductions: 900,
    tax: 1200,
    netSalary: 9900,
    status: 'PAID',
    paymentDate: '2026-07-25',
  },
  {
    id: 303,
    employeeId: 'EMP-003',
    employeeName: 'Sophia Chen',
    department: 'Engineering',
    designation: 'Engineering Lead',
    month: 'July 2026',
    basicSalary: 10500,
    allowances: 3250,
    deductions: 1000,
    tax: 1500,
    netSalary: 11250,
    status: 'PAID',
    paymentDate: '2026-07-25',
  },
  {
    id: 304,
    employeeId: 'EMP-004',
    employeeName: 'David Miller',
    department: 'Engineering',
    designation: 'Senior Frontend Engineer',
    month: 'July 2026',
    basicSalary: 8000,
    allowances: 2666,
    deductions: 800,
    tax: 1200,
    netSalary: 8666,
    status: 'PROCESSED',
    paymentDate: 'Pending Transfer',
  }
];

export const RECHARTS_DATA = {
  attendanceTrend: [
    { month: 'Feb', rate: 94.2, present: 108, absent: 6 },
    { month: 'Mar', rate: 96.5, present: 112, absent: 4 },
    { month: 'Apr', rate: 95.1, present: 110, absent: 5 },
    { month: 'May', rate: 97.8, present: 115, absent: 2 },
    { month: 'Jun', rate: 96.0, present: 113, absent: 4 },
    { month: 'Jul', rate: 98.4, present: 117, absent: 2 },
  ],
  deptDistribution: [
    { name: 'Engineering', value: 42, color: '#1F4D3B' },
    { name: 'Sales & Mkt', value: 29, color: '#F59E0B' },
    { name: 'Product', value: 18, color: '#2E7D57' },
    { name: 'Human Res', value: 14, color: '#6B4F3B' },
    { name: 'Finance/Legal', value: 10, color: '#2563EB' },
  ],
  salaryDistribution: [
    { range: '$60k-$90k', count: 24 },
    { range: '$90k-$120k', count: 48 },
    { range: '$120k-$150k', count: 28 },
    { range: '$150k-$180k', count: 12 },
    { range: '$180k+', count: 5 },
  ],
  monthlyHiring: [
    { month: 'Jan', hired: 6, exited: 1 },
    { month: 'Feb', hired: 4, exited: 2 },
    { month: 'Mar', hired: 8, exited: 0 },
    { month: 'Apr', hired: 5, exited: 1 },
    { month: 'May', hired: 9, exited: 2 },
    { month: 'Jun', hired: 7, exited: 1 },
    { month: 'Jul', hired: 10, exited: 0 },
  ],
  leaveAnalytics: [
    { type: 'Annual', used: 145, total: 300 },
    { type: 'Sick', used: 62, total: 200 },
    { type: 'Casual', used: 88, total: 180 },
    { type: 'Unpaid', used: 12, total: 50 },
  ]
};

export const NOTIFICATIONS = [
  {
    id: 1,
    title: 'New Leave Application',
    message: 'David Miller requested 5 days Annual Leave (Aug 04 - Aug 08).',
    time: '15 mins ago',
    read: false,
    type: 'leave',
  },
  {
    id: 2,
    title: 'Payroll Generated',
    message: 'July 2026 payroll slips for 113 employees have been compiled.',
    time: '2 hours ago',
    read: false,
    type: 'payroll',
  },
  {
    id: 3,
    title: 'New Team Onboarding',
    message: 'Amara Okafor completed HR profile verification.',
    time: 'Yesterday',
    read: true,
    type: 'employee',
  }
];

export const ACTIVITIES = [
  { id: 1, user: 'Marcus Sterling', action: 'Approved Leave Request', target: 'Liam Hemsworth', time: '10:14 AM Today' },
  { id: 2, user: 'Eleanor Vance', action: 'Created Department', target: 'Platform Engineering', time: 'Yesterday at 4:30 PM' },
  { id: 3, user: 'System Auto', action: 'Daily Attendance Report Compiled', target: '98.4% Present Rate', time: 'Yesterday at 9:00 AM' },
  { id: 4, user: 'Sophia Chen', action: 'Updated Designation', target: 'David Miller (Sr. Frontend)', time: '3 days ago' },
];
