<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Payment_module</RootNamespace>
    <UserSecretsId>2f3cbcdd-d825-4192-a7e4-43cbd563727c</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />

		<PackageReference Include="Razorpay" Version="3.3.2" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
	</ItemGroup>

</Project>
